version: 2
updates:
- package-ecosystem: npm
  directory: "/recently-contributed"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
  - dependency-name: ts-jest
    versions:
    - 26.5.2
