name: 'Recently contributed'
description: 'Gathers info about repositories recently contributed to'
inputs:
  github-token:
    description: 'Authentication token'
    required: true
  template-file:
    description: 'Template filepath'
    required: true
  output-file:
    description: 'Output filepath'
    required: true
  days:
    description: 'Number of days to look in the past'
    default: 28
runs:
  using: 'node12'
  main: 'dist/index.js'
