name: CI

on:
  push:
    branches:
      - master

jobs:
  rebuild:
    name: Rebuild
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: recently-contributed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install packages
        run: npm install
      - name: Run build
        run: npm run-script build
      - name: Setup git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Commit
        run: |
          git add -u
          git commit -m "Rebuild recently-contributed"
      - name: Push
        run: git push
